# **Numpy**



In [ ]:
import numpy as np

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
random_array = np.random.randint(10, 101, size=(3, 4))

print(random_array)

[[ 69  63  67  27]
 [ 10  52  40  59]
 [ 76  40  43 100]]


In [ ]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(arr_2d)
first_row = arr_2d[0, :]
print("First row:", first_row)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]


In [ ]:
import numpy as np

# Example 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

last_column = arr_2d[:, -1]

print("Last column:", last_column)

Last column: [3 6 9]


In [ ]:
a=np.array([[1,6,3],[7,3,9]])
b=np.array([[1,2,3],[4,5,6]])
sum=a+b
print(f"sum of two array {sum}")

sum of two array [[ 2  8  6]
 [11  8 15]]


In [ ]:
a=np.array([[6,3],[3,9]])
b=np.array([[1,3],[4,5,]])
dot=np.dot(a,b)
print(f"dot product of two array {dot}")

dot product of two array [[18 33]
 [39 54]]


In [ ]:
a=np.array([[1,6,3],[7,3,9]])
transpose= a.T
print(f"Tanaspose Of a is {transpose}")

Tanaspose Of a is [[1 7]
 [6 3]
 [3 9]]


# [**Pandas**](https://)

In [ ]:
import pandas as pd

In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math': [87, 92, 78, 90, 85],
    'Science': [88, 75, 91, 89, 92],
    'English': [84, 79, 86, 90, 88]
}

df = pd.DataFrame(data)
print(df)


      Name  Math  Science  English
0    Alice    87       88       84
1      Bob    92       75       79
2  Charlie    78       91       86
3    David    90       89       90
4      Eva    85       92       88


In [ ]:
Above_85=df[df['Math']>85]
print(Above_85)


    Name  Math  Science  English
0  Alice    87       88       84
1    Bob    92       75       79
3  David    90       89       90


In [ ]:
df["Avrage"]=df["Math"] + df["Science"] + df["English"]
df["Avrage"]=df["Avrage"]/3
print(df)

      Name  Math  Science  English     Avrage
0    Alice    87       88       84  86.333333
1      Bob    92       75       79  82.000000
2  Charlie    78       91       86  85.000000
3    David    90       89       90  89.666667
4      Eva    85       92       88  88.333333


In [ ]:
df["Total"]=df["Math"] + df["Science"] + df["English"]
print(df)

      Name  Math  Science  English     Avrage  Total
0    Alice    87       88       84  86.333333    259
1      Bob    92       75       79  82.000000    246
2  Charlie    78       91       86  85.000000    255
3    David    90       89       90  89.666667    269
4      Eva    85       92       88  88.333333    265


In [ ]:
Sorted_values=df.sort_values(by="Total",ascending=False)
print(df)


      Name  Math  Science  English     Avrage  Total
0    Alice    87       88       84  86.333333    259
1      Bob    92       75       79  82.000000    246
2  Charlie    78       91       86  85.000000    255
3    David    90       89       90  89.666667    269
4      Eva    85       92       88  88.333333    265


In [ ]:
Sorted_values=df.sort_values(by="Total",ascending=True)
print(df)


      Name  Math  Science  English     Avrage  Total
0    Alice    87       88       84  86.333333    259
1      Bob    92       75       79  82.000000    246
2  Charlie    78       91       86  85.000000    255
3    David    90       89       90  89.666667    269
4      Eva    85       92       88  88.333333    265
